### ISSUE TITLE
Unable to use building with rbenv-gemset

### ISSUE THREAD

**Issue by catkins** [CenturyLinkLabs/building#5]
I'm able to install the gem fine, but it doesn't seem to be playing nicely with rbenv gemset. I installed it globally, but i can't get it working when I'm in my app's directory which is using its own gemset.

```
$ cd ~/Dev
$ sudo gem install building
Fetching: building-1.1.2.gem (100%)
Successfully installed building-1.1.2
1 gem installed

$ building
Usage: building [options] CONTAINER_NAME [TAG]
    -o, --output FIGCONF             Output a fig configuration file
    -f, --from FROM                  Change the Dockerfile's FROM (chose from: ctlc/buildstep:ubuntu13.10, ctlc/buildstep:ubuntu13.04, ctlc/buildstep:ubuntu12.10, ctlc/buildstep:ubuntu12.04)
    -d, --dockerfile DOCKERFILE      External Dockerfile to append to the building generated Dockerfile
    -i, --include CMD                Extra commands during the image build
    -b, --buildpack URL              Add an external Buildpack URL
    -p, --p PORT                     Run the container after it is built on a certain port
    -h, --help                       Display this screen
```

So far so good..

```
$ cd my-rails-app
$ building
/usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/building-1.1.2/lib/building.rb:4:in `require': cannot load such file -- highline/import (LoadError)
  from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/building-1.1.2/lib/building.rb:4:in `<top (required)>'
  from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/building-1.1.2/bin/building:3:in `<top (required)>'
  from /usr/local/opt/rbenv/versions/2.0.0-p353/bin/building:23:in `load'
  from /usr/local/opt/rbenv/versions/2.0.0-p353/bin/building:23:in `<main>'
```

It can't seem to require `highline/import`. It loads fine in irb.

```
$ irb
irb(main):001:0> require 'highline/import'
=> true
```

I'm using rbenv-gemset 0.5.6 on OSX Mavericks.

Any ideas?

**Comment by eladg** [comment]
Same issue here while running outside of `bundle`, thanks @framallo for the temp solution.
